---
ID: "0f14005c-9576-412b-b7cc-45e61fa35fef"
Parent: "87c8da7f-fed1-44d2-82a7-d5a2c5c74909"
Template: "87c8da7f-fed1-44d2-82a7-d5a2c5c74909"
Path: /sitecore/templates/Project/Habitat SXA Sites/Habitat Home/Store/Account Management/My Order/__Standard Values
DB: master
SharedFields:
- ID: "d4952280-2d7d-4bf4-a99a-ea36dad0f0a7"
  Hint: Body Css Class
  Value: "my-order-page"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170811T075357Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
