---
ID: "39f84173-9873-495b-9288-8e0fe67e95fc"
Parent: "b4a26495-8b8d-401a-871d-0c120b680710"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Habitat Sites/Habitat Home Store/gulp/tasks/watchAll
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/A9C79883E99E42A78C8E496FDECF58EE.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "02a1b3f0-0a87-476f-a457-05c1ab6447b1"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGZzIGZyb20gJ2ZzJzsNCi8vDQppbXBvcnQgbG9naW4gZnJvbSAnLi9sb2dpbic7DQoNCg0KZ3VscC50YXNrKCdhbGwtd2F0Y2gnLCBbJ2xvZ2luJ10sDQogICAgZnVuY3Rpb24oKSB7DQogICAgICAgIGdsb2JhbC5pc1dhdGNoaW5nID0gdHJ1ZTsNCiAgICAgICAgZ3VscC5ydW4oJ3Nhc3Mtd2F0Y2gnKQ0KICAgICAgICBndWxwLnJ1bignanMtd2F0Y2gnKQ0KICAgICAgICBndWxwLnJ1bignY3NzLXdhdGNoJykNCiAgICAgICAgZ3VscC5ydW4oJ2ltZy13YXRjaCcpDQogICAgICAgIGd1bHAucnVuKCd3YXRjaC1zb3VyY2Utc2FzcycpDQogICAgICAgIGd1bHAucnVuKCdodG1sLXdhdGNoJykNCiAgICB9KQ0KDQpndWxwLnRhc2soJ2RlZmF1bHQnLCBbJ2FsbC13YXRjaCddKQ==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 478
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171108T075255Z
