---
ID: "0d9f38e1-8971-4d4c-bc2b-7880727786ce"
Parent: "7eda2f15-9386-4476-b13a-ede1c54c3980"
Template: "205f3ef7-05bb-452d-a338-1d0bb334267c"
Path: /sitecore/content/Habitat SXA Sites/Habitat Home/Settings/Commerce/Catalog Configuration
DB: master
SharedFields:
- ID: "55bcda17-f08b-40e7-b112-9945db903303"
  Hint: Catalog
  Value: "{59DDADC1-9B88-727E-9E14-3F6CF321AE0F}"
- ID: "d8950716-21ad-43c3-8763-74d8cd77c324"
  Hint: Include subcategory products
  Type: Checkbox
  Value: 1
- ID: "edeca58f-a268-4160-b609-e2944b3e459a"
  Hint: Start Navigation Category
  Value: "{B893C063-6238-ED57-700D-72862C56038D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180731T041049Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
