---
ID: "fa7b34cf-67a7-4950-a7fe-839328bd4e54"
Parent: "2f395077-da43-4935-b85c-29ae53a62f50"
Template: "2c7e608f-5450-4f6c-a990-b53526e7d35f"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/HabitatHome/Payment Configuration
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
- ID: "ee2d99c3-35c0-4467-8532-0e2aa960bb87"
  Hint: Payment Options
  Type: Multilist
  Value: |
    {0CFFAB11-2674-4A18-AB04-228B1F8A1DEC}
    {B5E5464E-C851-4C3C-8086-A4A874DD2DB0}
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{7352C784-37C8-4E69-8F2C-2174BA4A67CA}"
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Payment Configuration
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180204T191238Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
