---
ID: "f887bece-3a15-4c74-9537-267f676612ca"
Parent: "2f395077-da43-4935-b85c-29ae53a62f50"
Template: "9bb44636-1bd5-410c-86cb-b53663944cc3"
Path: /sitecore/Commerce/Commerce Control Panel/Storefront Settings/Storefronts/HabitatHome/Storefront Configuration
DB: master
SharedFields:
- ID: "0e4e60f6-cb5a-4971-9b9b-8f438a15213d"
  Hint: Enforce SSL
  Type: Checkbox
  Value: 1
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{BE2D0F3D-9D02-4C9E-825E-C1C75573834C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180204T191237Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\virtualssuser
